#!/bin/bash
alt {_,shift + } Return
		{st,st -c CenterTerminal}

alt + o ; {w,p,t,v,a}
		{brave,pcmanfm ~,telegram-desktop,st -e vifm ~,Waveform11}&
alt + d
		dmenu_run -i -l 5

alt +shift + s
		flameshot gui

alt + shift {e,w,n}
		~/dotfiles/exts/{dmn_power,words,symbols} &

alt + {g,y}
		~/exts/{class,yt}

shift + {p,w,e}
		~/dotfiles/exts/{pauseaudio,wp,emojis}

shift {u,d,m}
		amixer set Master {3+,3-,toggle};

shift + q
		pkill mpv; pkill sxiv

shift + {z,x}
		xbacklight {-dec,-inc} 5

ctrl + alt + {h, j, k,l}
		bspc node -z {left -20 0,bottom 0 20,top 0 -20,right 20 0}

alt {_,shift + } f
		bspc node -t {fullscreen,floating}

alt {_,shift + } q
		bspc node -{c,k}

alt + {t,shift + t}
		bspc node -t {tiled, pseudo_tiled}

alt + ctrl + {m,l,s,p}
		bspc node -g {marked,locked,sticky,private}

alt + {_,shift + }{h,j,k,l}
		bspc node -{f,s} {west,south,north,east}

alt + {_,shift + }{1-9,0}
		bspc {desktop -f,node -d} '^{1-9,10}';

alt + ctrl + {Left,Down,Up,Right}
		bspc node -v {-20 0,0 20,0 -20,20 0}
