#!/bin/sh

## Startup
pgrep xautolock | xautolock -time 5 -locker "amixer set Master mute && slock" &
#pgrep sxhkd | sxhkd &
pgrep polybar | polybar -r bar &

## Rules
bspc rule -r "*"
bspc monitor -d 1 2 3 4 5 6 7 8 9
bspc config border_width 1
bspc config borderless_monocle true
bspc config bottom_padding 0
bspc config focus_follows_pointer true
bspc config gapless_monocle true
bspc config pointer_action1 move
bspc config pointer_action2 resize_corner
bspc config pointer_modifier mod1
bspc config single_monocle true
bspc config split_ratio 0.50
bspc config top_padding 15
bspc config window_gap 2
bspc config bottom_padding 0
bspc config automatic_scheme alternate


## color
bspc config focused_border_color "#C0C0C0"
bspc config normal_border_color "#070707"
bspc config active_border_color "#1e1e1e"
bspc config presel_feedback_color "#5e81ac"
bspc config urgent_border_color "#dd2727"

#bspc subscribe desktop_focus | while read line; do notify-send "Current desktop:$(bspc query -D -d focused --names)"; done &

## Applications

# Floating
bspc rule -a CenterTerminal state=floating
bspc rule -a st state=floating
bspc rule -a Lxappearance state=floating
bspc rule -a Galculator state=floating
bspc rule -a MEGAsync state=floating
bspc rule -a Leafpad state=floating state=private
bspc rule -a Ardour-5.12.0 state=floating state=private
bspc rule -a QjackCtl state=floating
bspc rule -a Onboard state=floating
bspc rule -a Zathura state=tiled

# terminal
bspc rule -a Subl3 desktop='^1' follow=on

# Browser
bspc rule -a firefox desktop='^2' follow=on state=private
bspc rule -a Chromium desktop='^2' follow=on state=private
bspc rule -a Brave-browser desktop='^2' follow=on state=private
bspc rule -a Google-chrome desktop='^2' follow=on state=private

# image
bspc rule -a Gimp desktop='^4' follow=on

# video
bspc rule -a kdenlive desktop='^5' follow=on
bspc rule -a Olive desktop='^5' follow=on

#entertainment
bspc rule -a stremio desktop='^6' follow=on
bspc rule -a Audacious desktop='^6' follow=on

#Internet
bspc rule -a Filezilla desktop='^7' follow=on
bspc rule -a Qbitorrent desktop='^7' follow=on
bspc rule -a Anki desktop='^7' follow=on
bspc rule -a TelegramDesktop desktop='^7'

#Audio studio
bspc rule -a Hydrogen desktop='^8' follow=on
bspc rule -a REAPER desktop='^8' follow=on
bspc rule -a Ardour desktop='^9' follow=on
bspc rule -a waveform11 desktop='^9' follow=on
