#!/bin/bash
pgrep xautolock | xautolock -time 5 -locker "amixer set Master mute && slock" &

bspc rule -r "*"
bspc monitor -d 1 2 3 4 5 6 7 8 9
bspc config border_width 1
bspc config borderless_monocle true
bspc config bottom_padding 0
bspc config focus_follows_pointer true
bspc config gapless_monocle true
bspc config focused_border_color "#C0C0C0"
bspc config normal_border_color "#070707"
bspc config pointer_action1 move
bspc config pointer_action2 resize_corner
bspc config pointer_modifier mod1
bspc config single_monocle true
bspc config split_ratio 0.52
bspc config top_padding 0
bspc config window_gap 3
bspc config bottom_padding 15

bspc rule -a CenterTerminal state=floating
bspc rule -a Lxappearance state=floating
bspc rule -a Galculator state=floating
bspc rule -a MEGAsync state=floating
bspc rule -a Nitrogen state=floating
bspc rule -a Leafpad state=floating state=private
bspc rule -a Ardour-5.12.0 state=floating state=private

bspc rule -a firefox desktop='^2' follow=on state=private
bspc rule -a Chromium desktop='^2' follow=on state=private

bspc rule -a Subl3 desktop='^3' follow=on
bspc rule -a Gimp desktop='^3' follow=on

bspc rule -a kdenlive desktop='^4' follow=on
bspc rule -a Olive desktop='^4' follow=on
bspc rule -a Anki desktop='^4' follow=on

bspc rule -a Filezilla desktop='^6' follow=on
bspc rule -a Qbitorrent desktop='^6' follow=on

bspc rule -a TelegramDesktop desktop='^7'

bspc rule -a  Joplin desktop='^8' follow=on
bspc rule -a Ardour desktop='^8'	follow=on
bspc rule -a QjackCtl desktop='^9' follow=on
