#!/bin/bash
alt {_,shift + } Return
		{st,st -c CenterTerminal}

alt + o ; {w,p,t,v}
		{firefox,pcmanfm ~,telegram-desktop,st -e vifm ~}&
alt + d
		dmenu_run -i -l 5
alt + l
		pkill mpv; pkill sxiv

alt +shift + s
		flameshot gui

alt + shift {e,w,l}
		~/Documents/dotfiles/exts/{dmn_power,words,emojis} &

alt + {g,y,n,w}
		~/Documents/dotfiles/exts/{class,yt,symbols,wp}

shift {u,d,m}
		amixer set Master {3+,3-,toggle};

shift {p,d}
		mpc {toggle,repeat}

shift + {z,x}
		xbacklight {-dec,-inc} 5

ctrl + alt + {Left, Down, Up, Right}
		bspc node -z {left -20 0,bottom 0 20,top 0 -20,right 20 0}

alt {_,shift + } f
		bspc node -t {fullscreen,floating}

alt {_,shift + } q
		bspc node -{c,k}

alt + {t,shift + t}
		bspc node -t {tiled, pseudo_tiled}

alt + ctrl + {m,l,s,p}
		bspc node -g {marked,locked,sticky,private}

alt + {_,shift + }{Left,Down,Up,Right}
		bspc node -{f,s} {west,south,north,east}

alt + {_,shift + }{1-9,0}
		bspc {desktop -f,node -d} '^{1-9,10}';

alt + ctrl + {Left,Down,Up,Right}
		bspc node -v {-20 0,0 20,0 -20,20 0}
