#!/bin/bash
alt {_,shift + } Return
		{st,st -c CenterTerminal}

alt + o ; {w,p,f,q,t,v}
		{firefox,pcmanfm ~,filezilla,Qbitorrent,telegram-desktop,st -e vifm ~}&

alt + s ; {q,a}
		{qjackctl, ardour5}

alt + {d,p,k}
		rofi -show {run,windowcd,calc}
alt + l
		pkill mpv; pkill sxiv; pkill feh
alt {_,shift+ } + l
		{scrot, scrot -s} ~/documents/file.jpg

shift + {k,p,e}
		~/Documents/dotfiles/exts/{color,under,emojis}
alt + shift {e,w,n}
		~/Documents/dotfiles/exts/{dmn_power,words,symbols} &

alt + {g,y,n}
		~/Documents/dotfiles/exts/{class,yt}

shift {u,d,m}
		~/Documents/dotfiles/exts/vol {up,down,toggle} &

shift {p,d}
		mpc {toggle,repeat}

shift + {z,x}
		xbacklight {-dec,-inc} 5

ctrl + alt + {Left, Down, Up, Right}
		bspc node -z {left -20 0,bottom 0 20,top 0 -20,right 20 0}

alt {_,shift + } f
		bspc node -t {fullscreen,floating}

alt {_,shift + } q
		bspc node -{c,k}

alt + {t,shift + t}
		bspc node -t {tiled, pseudo_tiled}

alt + ctrl + {m,l,s,p}
		bspc node -g {marked,locked,sticky,private}

alt + {_,shift + }{Left,Down,Up,Right}
		bspc node -{f,s} {west,south,north,east}

alt + {_,shift + }{1-9,0}
		bspc {desktop -f,node -d} '^{1-9,10}';

alt + ctrl + {Left,Down,Up,Right}
		bspc node -v {-20 0,0 20,0 -20,20 0}
