#!/bin/sh
cd ~/dotfiles/suckless/dwm || exit
sudo make clean
cd ~/dotfiles/suckless/dmenu || exit
rm *.rej; sudo make clean
cd ~/dotfiles/suckless/st || exit
sudo make clean
cd ~/dotfiles/suckless/dwmblocks || exit
sudo make clean
cd ~/dotfiles/audacious/.config/audacious/ || exit
sudo rm -r lyrics playlists
cd ~/dotfiles/
git status .
