#!/bin/sh
sudo pacman -Syu --overwrite='*'
yay
echo "Searching for pip updates" && sudo pip install --upgrade pip
sudo pip list --outdated | awk 'NR >2 { print $1}' | xargs -I {} sudo pip install --upgrade "{}"
sudo pacman -Rsn $(pacman -Qtdq) && echo "Listing unnecessary packages"
echo "Wiping out cache and history" && sudo pacman -Sc --noconfirm >/dev/null 2>&1
echo "$(find ~ -type d -empty -print -delete | wc -l) empty folders deleted."
