#!/bin/sh
url="$(xclip -o)"
cd ~/Downloads/ || exit
case "$(printf "🎵 Download audio\n📼 Download video\n🖼 Download thumbnail\n📹 Open it with mpv" | dmenu -b -i -l 10)" in
		"🎵 Download audio") notify-send "⬇ Downloading audio" && youtube-dl -x -f bestaudio --audio-format vorbis -o '$HOME/Downloads/Music/%(title)s.%(ext)s' "$url" && dunstify "📼 Video has been Downloaded!" -r 250 &;;
		"📼 Download video") notify-send "⬇ Downloading video" &&  youtube-dl -f best -o '$HOME/Downloads/Videos/%(title)s.%(ext)s' "$url" && dunstify "🎵 Song has been Downloaded!" -r 250 &;;
		"🖼 Download thumbnail") notify-send "⬇ Downloading thumbnail" && youtube-dl --write-thumbnail --skip-download -o '$HOME/Downloads/Pictures/%(title)s.%(ext)s'} "$url" && dunstify "🖼 Thumbnail has been Downloaded!" -r 250 &;;
		"📹 Open it with mpv") notify-send "📹 Open it with mpv" && mpv "$url" &;;
esac
