#!/bin/sh
text="$(xclip -o)"
Symbols="
ai | #FF1601
ei | #13B2B2
ee | #FFA3BD
ih | #FFC20E
uh | #959105
eh | #31D0FF
an | #FF6D00
ae | #088354
o  | #87360F
ow | #7A2B80
uw | #9F9DC5
aw | #030DD7
ɔɪ | blank
Ʊ  | #C29260
'uh | #61B501
"
#color=
echo "<span style='color:$(echo "$Symbols" | dmenu -i -l 10 | awk '{print $3}' | tr -d '\n')'>$text</span>" | tr -d '\n' | xclip -selection clipboard
notify-send "$(xclip -o -selection clipboard) copied to clipboard"
