#!/bin/sh
emoji=$(cat ~/dotfiles/exts/emoji | rofi -dmenu -I -l 5 | cut -d ' ' -f1)
[ "$emoji" != "" ] || exit
echo "$emoji" | tr -d '\n' | xclip -selection clipboard
notify-send "$emoji copied to clipboard."
