#!/bin/sh
emoji=$(cat ~/Documents/dotfiles/exts/emoji | rofi -dmenu | cut -d ' ' -f1)
[ "$emoji" != "" ] || exit
echo "$emoji" | tr -d '\n' | xclip -selection clipboard
notify-send "$emoji copied to clipboard."
