#!/bin/sh
wget https://dwm.suckless.org/patches/pertag/dwm-pertag-20170513-ceac8c9.diff
wget https://dwm.suckless.org/patches/fakefullscreen/dwm-fakefullscreen-20170508-ceac8c9.diff
wget https://dwm.suckless.org/patches/gaplessgrid/dwm-gaplessgrid-20160731-56a31dc.diff
wget https://dwm.suckless.org/patches/monoclesymbol/dwm-monoclesymbol-6.2.diff
wget https://dwm.suckless.org/patches/notitle/dwm-notitle-6.2.diff
wget https://dwm.suckless.org/patches/center/dwm-center-6.1.diff
wget https://dwm.suckless.org/patches/centeredmaster/dwm-centeredmaster-6.1.diff
wget https://dwm.suckless.org/patches/movestack/dwm-movestack-6.1.diff
wget https://dwm.suckless.org/patches/noborder/dwm-noborder-6.2.diff
wget https://dwm.suckless.org/patches/fakefullscreen/dwm-fakefullscreen-20170508-ceac8c9.diff

patch < dwm-pertag-20170513-ceac8c9.diff
patch < dwm-fakefullscreen-20170508-ceac8c9.diff
patch < dwm-movestack-6.1.diff
patch < dwm-noborder-6.2.diff
patch < dwm-fakefullscreen-20170508-ceac8c9.diff
patch < dwm-center-6.1.diff
patch < dwm-notitle-6.2.diff
patch < dwm-monoclesymbol-6.2.diff
patch < dwm-gaplessgrid-20160731-56a31dc.diff
patch < dwm-centeredmaster-6.1.diff
rm *.diff
sudo pacman -S fd --noconfirm
