#!/bin/sh
Symbols="
–  | -
d͡ʒ | dj
tʃ | ch
·  | .
ə  | uh
æ  | ae
ə̃  | uh~
ɾ̃  | n
ɔɪ | oi
aɪ  | ai
ŋ  | ng
oʊ  | ou
aʊ | au
ɔ  | o
ʌ | 'uh
ɛ  | eh
ɪ  | ih
ɱ  | mf
ɸ  | f]
ɹ  | rr
ɾ  | dd
ʃ  | sh
ʊ  | uh
ʒ  | zh
ʔ  | glottal ?
ʰ  | h_
β  | v]
ð  | dth
θ  | th
—  | --
→  | ->
n̩ | n
ɝ | 'ur
ɚ | ur
"
echo "$Symbols" | dmenu -i -l 10 | awk '{print $1}' | tr -d '\n' | xclip -selection clipboard
notify-send "$(xclip -o -selection clipboard) copied to clipboard"
