#!/bin/sh
case "$1" in
        *.jpg|*.png|*.gif|*.jpeg|*.webp|*.jpeg_large) nohup sxiv -ab "$1" >/dev/null 2>&1 &;;
        *.mp4|*.webm|*.mkv|*youtube.com*) nohup mpv "$1" > /dev/null 2>&1 &;;
        *.ogg|*.mp3) nohup ffplay -loop 0 "$1" >/dev/null 2>&1 &;;
        *) st -e nvim "$1" ;;
esac
